insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (1, '2064 DSCTO PORTA', null, 12, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (2, '2065 DSCTO PORTA', null, 13, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (3, '2066 DSCTO PORTA', null, 6, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (4, '2067 DSCTO PORTA', null, 3, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (5, '2068 DSCTO PORTA', null, 1, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (6, 'MAX BENEFICIOS RRSS (PE)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (7, 'MAX BENEFICIOS RRSS (PE)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (8, 'MAX BENEFICIOS RRSS (PE)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (9, 'MAX BENEFICIOS RRSS (PE)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (10, 'MAX BENEFICIOS RRSS (PE)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (11, 'MAX BENEFICIOS RRSS (PE)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (12, 'MAX BENEFICIO RRSS (ME)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (13, 'MAX BENEFICIO RRSS (ME)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (14, 'MAX BENEFICIO RRSS (ME)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (15, 'MAX BENEFICIO RRSS (ME)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (16, 'MAX BENEFICIO RRSS (ME)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (17, 'MAX BENEFICIO RRSS (ME)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (18, 'MAX BENEFICIO RRSS (GE)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (19, 'MAX BENEFICIO RRSS (GE)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (20, 'MAX BENEFICIO RRSS (GE)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (21, 'MAX BENEFICIO RRSS (GE)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (22, 'MAX BENEFICIO RRSS (GE)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (23, 'MAX BENEFICIO RRSS (GE)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (24, 'MAX BENEFICIO RRSS (ESPECIAL)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (25, 'MAX BENEFICIO RRSS (ESPECIAL)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (26, 'MAX BENEFICIO RRSS (ESPECIAL)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (27, 'MAX BENEFICIO RRSS (ESPECIAL)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (28, 'MAX BENEFICIO RRSS (ESPECIAL)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (29, 'MAX BENEFICIO RRSS (ESPECIAL)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (30, 'MAX BENEFICIO DUPLICA TUS MB (PE)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (31, 'MAX BENEFICIO DUPLICA TUS MB (PE)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (32, 'MAX BENEFICIO DUPLICA TUS MB (PE)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (33, 'MAX BENEFICIO DUPLICA TUS MB (PE)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (34, 'MAX BENEFICIO DUPLICA TUS MB (PE)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (35, 'MAX BENEFICIO DUPLICA TUS MB (PE)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (36, 'MAX BENEFICIO DUPLICA TUS MB (ME)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (37, 'MAX BENEFICIO DUPLICA TUS MB (ME)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (38, 'MAX BENEFICIO DUPLICA TUS MB (ME)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (39, 'MAX BENEFICIO DUPLICA TUS MB (ME)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (40, 'MAX BENEFICIO DUPLICA TUS MB (ME)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (41, 'MAX BENEFICIO DUPLICA TUS MB (ME)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (42, 'MAX BENEFICIO DUPLICA TUS MB (GE)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (43, 'MAX BENEFICIO DUPLICA TUS MB (GE)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (44, 'MAX BENEFICIO DUPLICA TUS MB (GE)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (45, 'MAX BENEFICIO DUPLICA TUS MB (GE)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (46, 'MAX BENEFICIO DUPLICA TUS MB (GE)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (47, 'MAX BENEFICIO DUPLICA TUS MB (GE)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (48, 'MAX BENEFICIO DUPLICA TUS MB (ESPECIAL)', null, 12, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (49, 'MAX BENEFICIO DUPLICA TUS MB (ESPECIAL)', null, 13, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (50, 'MAX BENEFICIO DUPLICA TUS MB (ESPECIAL)', null, 4, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (51, 'MAX BENEFICIO DUPLICA TUS MB (ESPECIAL)', null, 8, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (52, 'MAX BENEFICIO DUPLICA TUS MB (ESPECIAL)', null, 3, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (53, 'MAX BENEFICIO DUPLICA TUS MB (ESPECIAL)', null, 15, '2  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (54, 'RENOVACIÓN ESPECIAL 79', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (55, 'RENOVACIÓN ESPECIAL 79', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (56, 'RENOVACIÓN ESPECIAL 79', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (57, 'RENOVACIÓN ESPECIAL 79', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (58, 'RENOVACIÓN ESPECIAL 79', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (59, 'RENOVACIÓN ESPECIAL 79', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (60, 'RENOVACIÓN ESPECIAL 79', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (61, 'RENOVACIÓN ESPECIAL 79', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (62, 'RENOVACIÓN ESPECIAL 79', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (63, 'RENOVACIÓN ESPECIAL 99', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (64, 'RENOVACIÓN ESPECIAL 99', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (65, 'RENOVACIÓN ESPECIAL 99', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (66, 'RENOVACIÓN ESPECIAL 99', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (67, 'RENOVACIÓN ESPECIAL 99', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (68, 'RENOVACIÓN ESPECIAL 99', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (69, 'RENOVACIÓN ESPECIAL 99', null, 10, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (70, 'RENOVACIÓN ESPECIAL 99', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (71, 'RENOVACIÓN ESPECIAL 99', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (72, 'RENOVACIÓN ESPECIAL 119', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (73, 'RENOVACIÓN ESPECIAL 119', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (74, 'RENOVACIÓN ESPECIAL 119', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (75, 'RENOVACIÓN ESPECIAL 119', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (76, 'RENOVACIÓN ESPECIAL 119', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (77, 'RENOVACIÓN ESPECIAL 119', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (78, 'RENOVACIÓN ESPECIAL 119', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (79, 'RENOVACIÓN ESPECIAL 119', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (80, 'RENOVACIÓN ESPECIAL 119', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (81, 'RENOVACIÓN ESPECIAL 139', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (82, 'RENOVACIÓN ESPECIAL 139', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (83, 'RENOVACIÓN ESPECIAL 139', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (84, 'RENOVACIÓN ESPECIAL 139', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (85, 'RENOVACIÓN ESPECIAL 139', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (86, 'RENOVACIÓN ESPECIAL 139', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (87, 'RENOVACIÓN ESPECIAL 139', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (88, 'RENOVACIÓN ESPECIAL 139', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (89, 'RENOVACIÓN ESPECIAL 139', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (90, 'REN ESPECIAL EXCLUSIVA 79', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (91, 'REN ESPECIAL EXCLUSIVA 79', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (92, 'REN ESPECIAL EXCLUSIVA 79', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (93, 'REN ESPECIAL EXCLUSIVA 79', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (94, 'REN ESPECIAL EXCLUSIVA 79', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (95, 'REN ESPECIAL EXCLUSIVA 79', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (96, 'REN ESPECIAL EXCLUSIVA 79', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (97, 'REN ESPECIAL EXCLUSIVA 79', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (98, 'REN ESPECIAL EXCLUSIVA 79', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (99, 'REN ESPECIAL EXCLUSIVA 99', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (100, 'REN ESPECIAL EXCLUSIVA 99', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (101, 'REN ESPECIAL EXCLUSIVA 99', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (102, 'REN ESPECIAL EXCLUSIVA 99', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (103, 'REN ESPECIAL EXCLUSIVA 99', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (104, 'REN ESPECIAL EXCLUSIVA 99', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (105, 'REN ESPECIAL EXCLUSIVA 99', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (106, 'REN ESPECIAL EXCLUSIVA 99', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (107, 'REN ESPECIAL EXCLUSIVA 99', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (108, 'REN ESPECIAL EXCLUSIVA 119', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (109, 'REN ESPECIAL EXCLUSIVA 119', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (110, 'REN ESPECIAL EXCLUSIVA 119', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (111, 'REN ESPECIAL EXCLUSIVA 119', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (112, 'REN ESPECIAL EXCLUSIVA 119', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (113, 'REN ESPECIAL EXCLUSIVA 119', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (114, 'REN ESPECIAL EXCLUSIVA 119', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (115, 'REN ESPECIAL EXCLUSIVA 119', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (116, 'REN ESPECIAL EXCLUSIVA 119', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (117, 'REN ESPECIAL EXCLUSIVA 139', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (118, 'REN ESPECIAL EXCLUSIVA 139', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (119, 'REN ESPECIAL EXCLUSIVA 139', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (120, 'REN ESPECIAL EXCLUSIVA 139', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (121, 'REN ESPECIAL EXCLUSIVA 139', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (122, 'REN ESPECIAL EXCLUSIVA 139', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (123, 'REN ESPECIAL EXCLUSIVA 139', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (124, 'REN ESPECIAL EXCLUSIVA 139', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (125, 'REN ESPECIAL EXCLUSIVA 139', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (126, 'REN ESPECIAL RETENCION 79', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (127, 'REN ESPECIAL RETENCION 79', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (128, 'REN ESPECIAL RETENCION 79', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (129, 'REN ESPECIAL RETENCION 79', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (130, 'REN ESPECIAL RETENCION 79', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (131, 'REN ESPECIAL RETENCION 79', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (132, 'REN ESPECIAL RETENCION 79', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (133, 'REN ESPECIAL RETENCION 79', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (134, 'REN ESPECIAL RETENCION 79', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (135, 'REN ESPECIAL RETENCION 99', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (136, 'REN ESPECIAL RETENCION 99', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (137, 'REN ESPECIAL RETENCION 99', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (138, 'REN ESPECIAL RETENCION 99', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (139, 'REN ESPECIAL RETENCION 99', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (140, 'REN ESPECIAL RETENCION 99', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (141, 'REN ESPECIAL RETENCION 99', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (142, 'REN ESPECIAL RETENCION 99', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (143, 'REN ESPECIAL RETENCION 99', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (144, 'REN ESPECIAL RETENCION 119', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (145, 'REN ESPECIAL RETENCION 119', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (146, 'REN ESPECIAL RETENCION 119', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (147, 'REN ESPECIAL RETENCION 119', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (148, 'REN ESPECIAL RETENCION 119', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (149, 'REN ESPECIAL RETENCION 119', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (150, 'REN ESPECIAL RETENCION 119', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (151, 'REN ESPECIAL RETENCION 119', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (152, 'REN ESPECIAL RETENCION 119', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (153, 'REN ESPECIAL RETENCION 139', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (154, 'REN ESPECIAL RETENCION 139', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (155, 'REN ESPECIAL RETENCION 139', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (156, 'REN ESPECIAL RETENCION 139', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (157, 'REN ESPECIAL RETENCION 139', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (158, 'REN ESPECIAL RETENCION 139', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (159, 'REN ESPECIAL RETENCION 139', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (160, 'REN ESPECIAL RETENCION 139', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (161, 'REN ESPECIAL RETENCION 139', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (162, 'CAMBIO DE PLAN ESPECIAL 125', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (163, 'CAMBIO DE PLAN ESPECIAL 125', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (164, 'CAMBIO DE PLAN ESPECIAL 125', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (165, 'CAMBIO DE PLAN ESPECIAL 125', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (166, 'CAMBIO DE PLAN ESPECIAL 125', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (167, 'CAMBIO DE PLAN ESPECIAL 125', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (168, 'CAMBIO DE PLAN ESPECIAL 125', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (169, 'CAMBIO DE PLAN ESPECIAL 125', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (170, 'CAMBIO DE PLAN ESPECIAL 125', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (171, 'CAMBIO DE PLAN ESPECIAL  105', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (172, 'CAMBIO DE PLAN ESPECIAL  105', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (173, 'CAMBIO DE PLAN ESPECIAL  105', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (174, 'CAMBIO DE PLAN ESPECIAL  105', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (175, 'CAMBIO DE PLAN ESPECIAL  105', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (176, 'CAMBIO DE PLAN ESPECIAL  105', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (177, 'CAMBIO DE PLAN ESPECIAL  105', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (178, 'CAMBIO DE PLAN ESPECIAL  105', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (179, 'CAMBIO DE PLAN ESPECIAL  105', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (180, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (181, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (182, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (183, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (184, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (185, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (186, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (187, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (188, 'CAMBIO DE PLAN ESPECIAL  85-2', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (189, 'CAMBIO DE PLAN ESPECIAL  85', null, 13, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (190, 'CAMBIO DE PLAN ESPECIAL  85', null, 14, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (191, 'CAMBIO DE PLAN ESPECIAL  85', null, 6, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (192, 'CAMBIO DE PLAN ESPECIAL  85', null, 5, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (193, 'CAMBIO DE PLAN ESPECIAL  85', null, 3, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (194, 'CAMBIO DE PLAN ESPECIAL  85', null, 8, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (195, 'CAMBIO DE PLAN ESPECIAL  85', null, 9, '3  ', 30);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (196, 'CAMBIO DE PLAN ESPECIAL  85', null, 10, '3  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (197, 'CAMBIO DE PLAN ESPECIAL  85', null, 11, '3  ', 62);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (198, '', 2, 5, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (199, '', 2, 2, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (200, '', 2, 13, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (201, '', 2, 14, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (202, '', 2, 3, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (203, '', 2, 1, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (204, '2064 DSCTO PORTA', null, 7, '4  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (205, '2064 DSCTO PORTA + BASE', null, 12, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (206, '2065 DSCTO PORTA + BASE', null, 13, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (207, '2066 DSCTO PORTA + BASE', null, 6, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (208, '2067 DSCTO PORTA + BASE', null, 3, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (209, '2068 DSCTO PORTA + BASE', null, 1, '1  ', null);

insert into MOTPROM.promt_campania_desactiva (IDCAMPANIADESA, CAMPANIA, IDOPERACION, IDDESACTIVACION, PRIORIDAD, TIEMPO)
values (210, '2068 DSCTO PORTA + BASE', null, 7, '4  ', null);

